### ISSUE TITLE
Cannot install using package manages

### ISSUE THREAD

**Issue by Rag0n** [kolinkrewinkel/Multiplex#24]
Installation is starting but few second after indicator rollbacks to initial state
Xcode version 7.1
Package managed 1.1.10

**Comment by kolinkrewinkel** [comment]
Unfortunately, Alcatraz won't support installing Multiplex for a while because we have CocoaPods dependencies that it can't/doesn't handle. Sorry for the inconvenience, there's an installer on the Releases page. The easiest thing to do IMO is to clone the repo and build the project. This'll let you easily install the latest stuff.
